### PR TITLE
[nrf fromtree] LwM2M 1.1 features from upstream

### PR DESCRIPTION
**Pull request by jheiskan81**

### CODE REVIEW

**Comment by jheiskan81** [comment]
@gmarull

**Comment by gmarull** [comment]
Do all these commits come from upstream? They need to have a saucetag.

**Comment by jheiskan81** [comment]
yes they come. I can add sauce tag's.

**Comment by gmarull** [comment]
if they have been merge just cherry-pick from upstream (with -x option) and use `[nrf fromtree]`

**Pull request merged**
